version: "3.6"
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    networks:
      - hadoopspark
    volumes:
      - shared-workspace:/opt/workspace
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
      - 9000:9000

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    networks:
      - hadoopspark
    volumes:
      - shared-workspace:/opt/workspace
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    depends_on:
      - namenode

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    networks:
      - hadoopspark
    volumes:
      - shared-workspace:/opt/workspace
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    networks:
      - hadoopspark
    volumes:
      - shared-workspace:/opt/workspace
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode
      - resourcemanager

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    networks:
      - hadoopspark
    volumes:
      - shared-workspace:/opt/workspace
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    networks:
      - hadoopspark
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    volumes:
      - shared-workspace:/opt/workspace
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    networks:
      - hadoopspark
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 hive-metastore-postgresql:5432"
    volumes:
      - shared-workspace:/opt/workspace
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - hadoopspark

  jupyterhub:
    image: jupyterhub-run_pyr
    container_name: jupyterhub
    ports:
      - 8888:8000
      - 8787:8787
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - hadoopspark

  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - hadoopspark

  spark-worker:
    image: spark-worker
    container_name: spark-worker
    environment:
      - SPARK_WORKER_CORES=12
      - SPARK_WORKER_MEMORY=1024m
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      - hadoopspark

volumes:
  namenode:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /host_mnt/d/Docker/volume/hadoop/namenode
  datanode:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /host_mnt/d/Docker/volume/hadoop/datanode
  hadoop_historyserver:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /host_mnt/d/Docker/volume/hadoop/historyserver
  shared-workspace:
    name: "shared-workspace"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /host_mnt/e/scripts/data-engineer-practice

networks:
  hadoopspark:
    name: hadoopspark